#App copies
replicaCount: 2

#Docker image
image:
  repository: ghcr.io/placeholder/task-manager
  tag: latest
  pullPolicy: IfNotPresent #if image not on server

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  host: task-manager.local
  path: /
  pathType: Prefix

mongodb:
  uri: "from_ci_CD"
  existingSecret: ""
  existingSecretKey: "mongo-uri"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
