apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongodb
  labels:
    app: task-manager
    release: {{ .Release.Name }}
type: Opaque
data:
  mongo-uri: {{ .Values.mongodb.uri | quote }}